/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#474745",
        "inverse-primary": "#c8c6c4",
        "on-surface": "#1a1c1a",
        "on-tertiary-fixed": "#0e1f10",
        "on-secondary-fixed": "#1d1c16",
        "on-primary-fixed": "#1b1c1a",
        "on-error-container": "#93000a",
        "tertiary-container": "#e8ffe4",
        "primary": "#5e5e5c",
        "on-secondary-fixed-variant": "#494740",
        "on-tertiary-container": "#637762",
        "surface-container-low": "#f4f4f0",
        "inverse-on-surface": "#f1f1ed",
        "surface-container-highest": "#e2e3df",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c8c6c4",
        "on-tertiary": "#ffffff",
        "surface": "#faf9f6",
        "surface-variant": "#e2e3df",
        "surface-container-lowest": "#ffffff",
        "background": "#faf9f6",
        "primary-container": "#faf8f5",
        "primary-fixed": "#e4e2df",
        "outline": "#757873",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#b7ccb4",
        "surface-container-high": "#e8e8e5",
        "tertiary-fixed": "#d2e9cf",
        "surface-container": "#eeeeea",
        "secondary": "#615e57",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#cac6bd",
        "surface-dim": "#dadad7",
        "on-tertiary-fixed-variant": "#394b39",
        "on-secondary-container": "#67645d",
        "surface-tint": "#5e5e5c",
        "tertiary": "#50634f",
        "secondary-container": "#e7e2d9",
        "on-background": "#1a1c1a",
        "secondary-fixed": "#e7e2d9",
        "on-primary-container": "#727270",
        "error": "#ba1a1a",
        "on-surface-variant": "#454843",
        "outline-variant": "#c5c7c1",
        "surface-bright": "#faf9f6",
        "inverse-surface": "#2f312f",
        "sage": "#637762",
      },
      borderRadius: {
        DEFAULT: "0px",
        none: "0px",
      },
      spacing: {
        "margin-mobile": "24px",
        "margin-desktop": "64px",
        "gutter": "32px",
        "unit": "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        serif: ["EB Garamond", "serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
}
